## box is a list of commands
## a command is a dictionary containing a list of tags that uniquely identify it
## along with all the information needed to run the command
box = [
    {'service': 'L', 'args':{ 'roomid':'1362520', 'machinetype':'washer', 'label': 'DUNSTER HOUSE K Washers'}, 'tags': ['DUNSTER', 'HOUSE', 'K', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362520', 'machinetype':'dryer', 'label': 'DUNSTER HOUSE K Dryers'}, 'tags': ['DUNSTER', 'HOUSE', 'K', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362521', 'machinetype':'washer', 'label': 'DUNSTER HOUSE G Washers'}, 'tags': ['DUNSTER', 'HOUSE', 'G', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362521', 'machinetype':'dryer', 'label': 'DUNSTER HOUSE G Dryers'}, 'tags': ['DUNSTER', 'HOUSE', 'G', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'144633', 'machinetype':'washer', 'label': '10 DEWOLFE STREET Washers'}, 'tags': ['10', 'DEWOLFE', 'STREET', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'144633', 'machinetype':'dryer', 'label': '10 DEWOLFE STREET Dryers'}, 'tags': ['10', 'DEWOLFE', 'STREET', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362589', 'machinetype':'washer', 'label': 'STOUGHTON HALL Washers'}, 'tags': ['STOUGHTON', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362589', 'machinetype':'dryer', 'label': 'STOUGHTON HALL Dryers'}, 'tags': ['STOUGHTON', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362540', 'machinetype':'washer', 'label': 'CABOT HOUSE - BRIGGS HALL Washers'}, 'tags': ['CABOT', 'HOUSE', '-', 'BRIGGS', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362540', 'machinetype':'dryer', 'label': 'CABOT HOUSE - BRIGGS HALL Dryers'}, 'tags': ['CABOT', 'HOUSE', '-', 'BRIGGS', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'washer', 'label': '1202 MASS AVE 4TH FLR LR Washers'}, 'tags': ['1202', 'MASS', 'AVE', '4TH', 'FLR', 'LR', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'dryer', 'label': '1202 MASS AVE 4TH FLR LR Dryers'}, 'tags': ['1202', 'MASS', 'AVE', '4TH', 'FLR', 'LR', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362531', 'machinetype':'washer', 'label': 'NEW QUINCY 6TH FLOOR Washers'}, 'tags': ['NEW', 'QUINCY', '6TH', 'FLOOR', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362531', 'machinetype':'dryer', 'label': 'NEW QUINCY 6TH FLOOR Dryers'}, 'tags': ['NEW', 'QUINCY', '6TH', 'FLOOR', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362551', 'machinetype':'washer', 'label': 'CURRIER HOUSE - GILBERT HALL Washers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'GILBERT', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362551', 'machinetype':'dryer', 'label': 'CURRIER HOUSE - GILBERT HALL Dryers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'GILBERT', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362513', 'machinetype':'washer', 'label': 'PFORZHEIMER HOUSE - COMSTOCK HALL Washers'}, 'tags': ['PFORZHEIMER','PFOHO', 'POOH', 'HOUSE', '-', 'COMSTOCK', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362513', 'machinetype':'dryer', 'label': 'PFORZHEIMER HOUSE - COMSTOCK HALL Dryers'}, 'tags': ['PFORZHEIMER','PFOHO', 'POOH','HOUSE', '-', 'COMSTOCK', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362541', 'machinetype':'washer', 'label': 'HURLBUT HALL Washers'}, 'tags': ['HURLBUT', 'HURL', 'PENNYPACKER', 'PENNY', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362541', 'machinetype':'dryer', 'label': 'HURLBUT HALL Dryers'}, 'tags': ['HURLBUT', 'HURL', 'PENNYPACKER', 'PENNY', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'washer', 'label': '22 PRESCOTT ST Washers'}, 'tags': ['22', 'PRESCOTT', 'ST', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'dryer', 'label': '22 PRESCOTT ST Dryers'}, 'tags': ['22', 'PRESCOTT', 'ST', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362530', 'machinetype':'washer', 'label': 'LEVERETT HOUSE MCKINLOCK Washers'}, 'tags': ['LEVERETT', 'HOUSE', 'MCKINLOCK', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362530', 'machinetype':'dryer', 'label': 'LEVERETT HOUSE MCKINLOCK Dryers'}, 'tags': ['LEVERETT', 'HOUSE', 'MCKINLOCK', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362514', 'machinetype':'washer', 'label': 'PFORZHEIMER HOUSE - MOORS HALL Washers'}, 'tags': ['PFORZHEIMER','PFOHO', 'POOH','HOUSE', '-', 'MOORS', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362514', 'machinetype':'dryer', 'label': 'PFORZHEIMER HOUSE - MOORS HALL Dryers'}, 'tags': ['PFORZHEIMER','PFOHO','POOH', 'HOUSE', '-', 'MOORS', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362549', 'machinetype':'washer', 'label': 'PFORZHEIMER HOUSE - HOLMES HALL Washers'}, 'tags': ['PFORZHEIMER','PFOHO', 'POOH','HOUSE', '-', 'HOLMES', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362549', 'machinetype':'dryer', 'label': 'PFORZHEIMER HOUSE - HOLMES HALL Dryers'}, 'tags': ['PFORZHEIMER','PFOHO', 'POOH','HOUSE', '-', 'HOLMES', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362557', 'machinetype':'washer', 'label': 'PFORZHEIMER HOUSE - JORDAN SOUTH Washers'}, 'tags': ['PFORZHEIMER','PFOHO', 'POOH','HOUSE', '-', 'JORDAN', 'SOUTH', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362557', 'machinetype':'dryer', 'label': 'PFORZHEIMER HOUSE - JORDAN SOUTH Dryers'}, 'tags': ['PFORZHEIMER','PFOHO','POOH', 'HOUSE', '-', 'JORDAN', 'SOUTH', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362585', 'machinetype':'washer', 'label': 'CURRIER HOUSE - DANIELS HALL Washers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'DANIELS', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362585', 'machinetype':'dryer', 'label': 'CURRIER HOUSE - DANIELS HALL Dryers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'DANIELS', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362546', 'machinetype':'washer', 'label': 'ADAMS HOUSE Washers'}, 'tags': ['ADAMS', 'HOUSE', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362546', 'machinetype':'dryer', 'label': 'ADAMS HOUSE Dryers'}, 'tags': ['ADAMS', 'HOUSE', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362528', 'machinetype':'washer', 'label': 'LOWELL HOUSE G  Washers'}, 'tags': ['LOWELL', 'HOUSE', 'G', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362528', 'machinetype':'dryer', 'label': 'LOWELL HOUSE G  Dryers'}, 'tags': ['LOWELL', 'HOUSE', 'G', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'washer', 'label': '1201 MASS AVE 3RD FLR LR Washers'}, 'tags': ['1201', 'MASS', 'AVE', '3RD', 'FLR', 'LR', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'dryer', 'label': '1201 MASS AVE 3RD FLR LR Dryers'}, 'tags': ['1201', 'MASS', 'AVE', '3RD', 'FLR', 'LR', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362514', 'machinetype':'washer', 'label': '24 PRESCOTT ST Washers'}, 'tags': ['24', 'PRESCOTT', 'ST', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362514', 'machinetype':'dryer', 'label': '24 PRESCOTT ST Dryers'}, 'tags': ['24', 'PRESCOTT', 'ST', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'014711', 'machinetype':'washer', 'label': '8 PLYMPTON STREET Washers'}, 'tags': ['8', 'PLYMPTON', 'STREET', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'014711', 'machinetype':'dryer', 'label': '8 PLYMPTON STREET Dryers'}, 'tags': ['8', 'PLYMPTON', 'STREET', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362527', 'machinetype':'washer', 'label': 'LEVERETT HOUSE G TOWER Washers'}, 'tags': ['LEVERETT', 'HOUSE', 'G', 'TOWER', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362527', 'machinetype':'dryer', 'label': 'LEVERETT HOUSE G TOWER Dryers'}, 'tags': ['LEVERETT', 'HOUSE', 'G', 'TOWER', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362588', 'machinetype':'washer', 'label': 'THAYER HALL Washers'}, 'tags': ['THAYER', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362588', 'machinetype':'dryer', 'label': 'THAYER HALL Dryers'}, 'tags': ['THAYER', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362537', 'machinetype':'washer', 'label': 'CABOT HOUSE - ELLIOT HALL Washers'}, 'tags': ['CABOT', 'HOUSE', '-', 'ELLIOT', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362537', 'machinetype':'dryer', 'label': 'CABOT HOUSE - ELLIOT HALL Dryers'}, 'tags': ['CABOT', 'HOUSE', '-', 'ELLIOT', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362547', 'machinetype':'washer', 'label': 'APLEY COURT Washers'}, 'tags': ['APLEY', 'APPLY', 'COURT', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362547', 'machinetype':'dryer', 'label': 'APLEY COURT Dryers'}, 'tags': ['APLEY', 'APPLY', 'COURT', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362525', 'machinetype':'washer', 'label': 'KIRKLAND HOUSE J Washers'}, 'tags': ['KIRKLAND', 'HOUSE', 'J', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362525', 'machinetype':'dryer', 'label': 'KIRKLAND HOUSE J Dryers'}, 'tags': ['KIRKLAND', 'HOUSE', 'J', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362554', 'machinetype':'washer', 'label': 'PFORZHEIMER HOUSE - WOLBACH HALL Washers'}, 'tags': ['PFORZHEIMER','PFOHO', 'HOUSE', '-', 'WOLBACH', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362554', 'machinetype':'dryer', 'label': 'PFORZHEIMER HOUSE - WOLBACH HALL Dryers'}, 'tags': ['PFORZHEIMER','PFOHO', 'HOUSE', '-', 'WOLBACH', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362529', 'machinetype':'washer', 'label': 'LOWELL HOUSE D Washers'}, 'tags': ['LOWELL', 'HOUSE', 'D', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362529', 'machinetype':'dryer', 'label': 'LOWELL HOUSE D Dryers'}, 'tags': ['LOWELL', 'HOUSE', 'D', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362552', 'machinetype':'washer', 'label': 'CURRIER HOUSE - TUCHMAN HALL Washers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'TUCHMAN', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362552', 'machinetype':'dryer', 'label': 'CURRIER HOUSE - TUCHMAN HALL Dryers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'TUCHMAN', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362533', 'machinetype':'washer', 'label': '1306 MASS AVE Washers'}, 'tags': ['1306', 'MASS', 'AVE', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362533', 'machinetype':'dryer', 'label': '1306 MASS AVE Dryers'}, 'tags': ['1306', 'MASS', 'AVE', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'13625933', 'machinetype':'washer', 'label': 'STONE HALL  Washers'}, 'tags': ['STONE', 'HALL', 'QUINCY', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'13625933', 'machinetype':'dryer', 'label': 'STONE HALL  Dryers'}, 'tags': ['STONE', 'HALL', 'QUINCY', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'136259', 'machinetype':'washer', 'label': 'WELD HALL Washers'}, 'tags': ['WELD', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'136259', 'machinetype':'dryer', 'label': 'WELD HALL Dryers'}, 'tags': ['WELD', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'144634', 'machinetype':'washer', 'label': '20 DEWOLFE STREET Washers'}, 'tags': ['20', 'DEWOLFE', 'STREET', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'144634', 'machinetype':'dryer', 'label': '20 DEWOLFE STREET Dryers'}, 'tags': ['20', 'DEWOLFE', 'STREET', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362526', 'machinetype':'washer', 'label': 'LEVERETT HOUSE F TOWER Washers'}, 'tags': ['LEVERETT', 'HOUSE', 'F', 'TOWER', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362526', 'machinetype':'dryer', 'label': 'LEVERETT HOUSE F TOWER Dryers'}, 'tags': ['LEVERETT', 'HOUSE', 'F', 'TOWER', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362523', 'machinetype':'washer', 'label': 'ELIOT HOUSE J Washers'}, 'tags': ['ELIOT','ELLIOT', 'HOUSE', 'J', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362523', 'machinetype':'dryer', 'label': 'ELIOT HOUSE J Dryers'}, 'tags': ['ELIOT', 'ELLIOT', 'HOUSE', 'J', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362584', 'machinetype':'washer', 'label': 'CANADAY HALL Washers'}, 'tags': ['CANADAY', 'CANDY', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362584', 'machinetype':'dryer', 'label': 'CANADAY HALL Dryers'}, 'tags': ['CANADAY','CANDY', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362539', 'machinetype':'washer', 'label': 'PFORZHEIMER HOUSE - JORDAN NORTH Washers'}, 'tags': ['PFORZHEIMER','PFOHO', 'POOH', 'HOUSE', '-', 'JORDAN', 'NORTH', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362539', 'machinetype':'dryer', 'label': 'PFORZHEIMER HOUSE - JORDAN NORTH Dryers'}, 'tags': ['PFORZHEIMER','PFOHO','POOH', 'HOUSE', '-', 'JORDAN', 'NORTH', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362510', 'machinetype':'washer', 'label': 'CURRIER HOUSE - BINGHAM HALL Washers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'BINGHAM', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362510', 'machinetype':'dryer', 'label': 'CURRIER HOUSE - BINGHAM HALL Dryers'}, 'tags': ['CURRIER', 'HOUSE', '-', 'BINGHAM', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362535', 'machinetype':'washer', 'label': 'WINTHROP - STANDISH Washers'}, 'tags': ['WINTHROP', '-', 'STANDISH', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362535', 'machinetype':'dryer', 'label': 'WINTHROP - STANDISH Dryers'}, 'tags': ['WINTHROP', '-', 'STANDISH', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362511', 'machinetype':'washer', 'label': 'CABOT HOUSE - BERTRAM HALL Washers'}, 'tags': ['CABOT', 'HOUSE', '-', 'BERTRAM', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362511', 'machinetype':'dryer', 'label': 'CABOT HOUSE - BERTRAM HALL Dryers'}, 'tags': ['CABOT', 'HOUSE', '-', 'BERTRAM', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362545', 'machinetype':'washer', 'label': 'KIRKLAND HOUSE G Washers'}, 'tags': ['KIRKLAND', 'HOUSE', 'G', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362545', 'machinetype':'dryer', 'label': 'KIRKLAND HOUSE G Dryers'}, 'tags': ['KIRKLAND', 'HOUSE', 'G', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'washer', 'label': '20 PRESCOTT ST Washers'}, 'tags': ['20', 'PRESCOTT', 'ST', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362515', 'machinetype':'dryer', 'label': '20 PRESCOTT ST Dryers'}, 'tags': ['20', 'PRESCOTT', 'ST', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362518', 'machinetype':'washer', 'label': 'WIGGLESWORTH HALL Washers'}, 'tags': ['WIGGLESWORTH','WIGG', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362518', 'machinetype':'dryer', 'label': 'WIGGLESWORTH HALL Dryers'}, 'tags': ['WIGGLESWORTH','WIGG', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362586', 'machinetype':'washer', 'label': 'LOWELL HOUSE N Washers'}, 'tags': ['LOWELL', 'HOUSE', 'N', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362586', 'machinetype':'dryer', 'label': 'LOWELL HOUSE N Dryers'}, 'tags': ['LOWELL', 'HOUSE', 'N', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362516', 'machinetype':'washer', 'label': 'GREENOUGH HALL Washers'}, 'tags': ['GREENOUGH', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362516', 'machinetype':'dryer', 'label': 'GREENOUGH HALL Dryers'}, 'tags': ['GREENOUGH', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362555', 'machinetype':'washer', 'label': 'CLAVERLY HALL Washers'}, 'tags': ['CLAVERLY', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362555', 'machinetype':'dryer', 'label': 'CLAVERLY HALL Dryers'}, 'tags': ['CLAVERLY', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362532', 'machinetype':'washer', 'label': 'NEW QUINCY BASEMENT STUDENT LAUNDRY Washers'}, 'tags': ['NEW', 'QUINCY', 'BASEMENT', 'STUDENT', 'LAUNDRY', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362532', 'machinetype':'dryer', 'label': 'NEW QUINCY BASEMENT STUDENT LAUNDRY Dryers'}, 'tags': ['NEW', 'QUINCY', 'BASEMENT', 'STUDENT', 'LAUNDRY', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362534', 'machinetype':'washer', 'label': '65 MOUNT AUBURN STREET Washers'}, 'tags': ['65', 'MOUNT', 'AUBURN', 'STREET', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362534', 'machinetype':'dryer', 'label': '65 MOUNT AUBURN STREET Dryers'}, 'tags': ['65', 'MOUNT', 'AUBURN', 'STREET', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362536', 'machinetype':'washer', 'label': 'WINTHROP - GORE Washers'}, 'tags': ['WINTHROP', '-', 'GORE', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362536', 'machinetype':'dryer', 'label': 'WINTHROP - GORE Dryers'}, 'tags': ['WINTHROP', '-', 'GORE', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362548', 'machinetype':'washer', 'label': 'MATHER HOUSE HIGH RISE Washers'}, 'tags': ['MATHER', 'HOUSE', 'HIGH', 'RISE', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362548', 'machinetype':'dryer', 'label': 'MATHER HOUSE HIGH RISE Dryers'}, 'tags': ['MATHER', 'HOUSE', 'HIGH', 'RISE', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362512', 'machinetype':'washer', 'label': 'CABOT HOUSE - WHITMAN HALL Washers'}, 'tags': ['CABOT', 'HOUSE', '-', 'WHITMAN', 'HALL', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362512', 'machinetype':'dryer', 'label': 'CABOT HOUSE - WHITMAN HALL Dryers'}, 'tags': ['CABOT', 'HOUSE', '-', 'WHITMAN', 'HALL', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'L', 'args':{ 'roomid':'1362556', 'machinetype':'washer', 'label': 'MATHER HOUSE LOW RISE Washers'}, 'tags': ['MATHER', 'HOUSE', 'LOW', 'RISE', 'LAUNDRY', 'WASHERS', 'WASHER']},
    {'service': 'L', 'args':{ 'roomid':'1362556', 'machinetype':'dryer', 'label': 'MATHER HOUSE LOW RISE Dryers'}, 'tags': ['MATHER', 'HOUSE', 'LOW', 'RISE', 'LAUNDRY', 'DRYER', 'DRYERS']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4070614' , 'label': 'Quad Shuttle Stop'}, 'tags':['QUAD', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4070630' , 'label': 'Mass Ave & Garden St Shuttle Stop'}, 'tags':['MASS', 'AVE', '&', 'GARDEN', 'ST', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4070634' , 'label': 'Memorial Hall Shuttle Stop'}, 'tags':['MEMORIAL', 'HALL', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4070638' , 'label': 'Lamont Library Shuttle Stop'}, 'tags':['LAMONT', 'LIBRARY', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4070642' , 'label': 'Widener Gate Shuttle Stop'}, 'tags':['WIDENER', 'GATE', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4070670' , 'label': 'Inn at Harvard Shuttle Stop'}, 'tags':['INN', 'AT', 'HARVARD', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4109006' , 'label': 'Law School Shuttle Stop'}, 'tags':['LAW', 'SCHOOL', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4125502' , 'label': 'Winthrop House Shuttle Stop'}, 'tags':['WINTHROP', 'HOUSE', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4130382' , 'label': 'Mather House Shuttle Stop'}, 'tags':['MATHER', 'HOUSE', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4166978' , 'label': 'Peabody Terrace Shuttle Stop'}, 'tags':['PEABODY', 'TERRACE', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190630' , 'label': 'Kennedy (Temporary Stop) Shuttle Stop'}, 'tags':['KENNEDY', '(TEMPORARY', 'STOP)', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190632' , 'label': 'Maxwell Dworkin Shuttle Stop'}, 'tags':['MAXWELL', 'DWORKIN', 'MD', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190634' , 'label': 'Harvard Square Shuttle Stop'}, 'tags':['HARVARD', 'SQUARE', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190636' , 'label': 'Stadium Shuttle Stop'}, 'tags':['STADIUM', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190638' , 'label': 'HiLab-HBS Shuttle Stop'}, 'tags':['HILAB-HBS', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190640' , 'label': 'Soldiers Field Park Shuttle Stop'}, 'tags':['SOLDIERS', 'FIELD', 'PARK', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190642' , 'label': 'Kennedy School Shuttle Stop'}, 'tags':['KENNEDY', 'SCHOOL', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190644' , 'label': 'i-Lab (Temporary) Shuttle Stop'}, 'tags':['I-LAB', '(TEMPORARY)', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190646' , 'label': 'Jordan Field Shuttle Stop'}, 'tags':['JORDAN', 'FIELD', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190648' , 'label': 'Stadium Complex (Gate #8) Shuttle Stop'}, 'tags':['STADIUM', 'COMPLEX', '(GATE', '#8)', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190650' , 'label': 'DeWolfe St. at Mill St. Area Shuttle Stop'}, 'tags':['DEWOLFE', 'ST.', 'AT', 'MILL', 'ST.', 'AREA', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190652' , 'label': 'Lamont Library Gate Shuttle Stop'}, 'tags':['LAMONT', 'LIBRARY', 'GATE', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190654' , 'label': 'Garden St. at Mason St. Shuttle Stop'}, 'tags':['GARDEN', 'ST.', 'AT', 'MASON', 'ST.', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190656' , 'label': '175 North Harvard Shuttle Stop'}, 'tags':['175', 'NORTH', 'HARVARD', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190660' , 'label': 'Soldiers Field Park (Temporary) Shuttle Stop'}, 'tags':['SOLDIERS', 'FIELD', 'PARK', '(TEMPORARY)', 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'stop', 'stopid': '4190662' , 'label': 'Barry\'s Corner Shuttle Stop'}, 'tags':["BARRY\'S", 'CORNER', "BARRY", 'SHUTTLE', 'STOP']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4003894' , 'label': 'Quad Express Shuttle Route'}, 'tags':['QUAD', 'EXPRESS', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4003906' , 'label': 'River House A Shuttle Route'}, 'tags':['RIVER', 'HOUSE', 'A', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4003910' , 'label': 'River House B Shuttle Route'}, 'tags':['RIVER', 'HOUSE', 'B', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4003914' , 'label': 'Quad Yard Express Shuttle Route'}, 'tags':['QUAD', 'YARD', 'EXPRESS', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4003934' , 'label': 'River House C Shuttle Route'}, 'tags':['RIVER', 'HOUSE', 'C', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4003938' , 'label': 'Extended Overnight Shuttle Route'}, 'tags':['EXTENDED', 'OVERNIGHT', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4007272' , 'label': 'Barry\'s Corner Shuttle Route'}, 'tags':["BARRY'S",'BARRY', 'CORNER', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4007610' , 'label': 'Quad Stadium Express Shuttle Route'}, 'tags':['QUAD', 'STADIUM', 'EXPRESS', 'SHUTTLE', 'ROUTE']},
    {'service': 'S', 'args':{'endpoint': 'route', 'routeid': '4007650' , 'label': 'Allston Campus Express Shuttle Route'}, 'tags':['ALLSTON', 'CAMPUS', 'EXPRESS', 'SHUTTLE', 'ROUTE']},
    {'service': 'W', 'args':{}, 'tags':['WEATHER']},
    {'service': 'D', 'args':{}, 'tags':['WORDOFTHEDAY']},
    {'service': 'MBTA', 'args': {'pg': ['green/lake']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'COLLEGE', 'BOSTON']},
    {'service': 'MBTA', 'args': {'pg': ['green/sougr']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'STREET', 'SOUTH', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/chill']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'HILL', 'AVE', 'GREEN', 'CHESTNUT']},
    {'service': 'MBTA', 'args': {'pg': ['green/chswk']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RD', 'CHISWICK', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/sthld']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'SUTHERLAND', 'RD']},
    {'service': 'MBTA', 'args': {'pg': ['green/wascm']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'WASHINGTON', 'STREET', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/wrnst']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'GREEN', 'STREET', 'WARREN']},
    {'service': 'MBTA', 'args': {'pg': ['green/alsgr']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ALLSTON', 'STREET', 'GREEN', 'ST']},
    {'service': 'MBTA', 'args': {'pg': ['green/grigg']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'GRIGGS', 'STREET', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/harvd']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'AVE', 'HARVARD', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/brico']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'PACKARDS', 'CORNER']},
    {'service': 'MBTA', 'args': {'pg': ['green/babck']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BABCOCK', 'ST', 'STREET', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/plsgr']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'PLEASANT', 'ST', 'STREET', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/stplb']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'PAUL', 'STREET', 'ST.', 'GREEN', 'ST']},
    {'service': 'MBTA', 'args': {'pg': ['green/buwst']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BU', 'GREEN', 'WEST']},
    {'service': 'MBTA', 'args': {'pg': ['green/bucen']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BU', 'GREEN', 'CENTRAL']},
    {'service': 'MBTA', 'args': {'pg': ['green/buest']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BU', 'GREEN', 'EAST']},
    {'service': 'MBTA', 'args': {'pg': ['green/bland']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'STREET', 'BLANDFORD', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/kencl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'KENMORE']},
    {'service': 'MBTA', 'args': {'pg': ['green/hymnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'HYNES', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/coecl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'COPLEY', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/armnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'ARLINGTON']},
    {'service': 'MBTA', 'args': {'pg': ['green/boyls']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BOYLSTON', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/clmnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'CIRCLE', 'GREEN', 'CLEVELAND']},
    {'service': 'MBTA', 'args': {'pg': ['green/engav']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'AVE', 'GREEN', 'ENGLEWOOD']},
    {'service': 'MBTA', 'args': {'pg': ['green/denrd']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'DEAN', 'RD', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/tapst']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'GREEN', 'STREET', 'TAPPAN']},
    {'service': 'MBTA', 'args': {'pg': ['green/bcnwa']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'WASHINGTON', 'SQUARE', 'GREEN', 'SQ']},
    {'service': 'MBTA', 'args': {'pg': ['green/fbkst']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'FAIRBANKS', 'STREET', 'GREEN', 'ST']},
    {'service': 'MBTA', 'args': {'pg': ['green/bndhl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BRANDON', 'GREEN', 'HALL']},
    {'service': 'MBTA', 'args': {'pg': ['green/sumav']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'AVE', 'SUMMIT', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/cool']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'COOLIDGE', 'CORNER']},
    {'service': 'MBTA', 'args': {'pg': ['green/stpul']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'PAUL', 'STREET', 'ST.', 'GREEN', 'ST']},
    {'service': 'MBTA', 'args': {'pg': ['green/kntst']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'GREEN', 'STREET', 'KENT']},
    {'service': 'MBTA', 'args': {'pg': ['green/hwsst']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'HAWES', 'ST', 'STREET', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/smary']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ST', 'MARYS', 'STREET', 'ST.', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/kencl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'KENMORE']},
    {'service': 'MBTA', 'args': {'pg': ['green/hymnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'HYNES', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/coecl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'COPLEY', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/armnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'ARLINGTON']},
    {'service': 'MBTA', 'args': {'pg': ['green/boyls']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BOYLSTON', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/river']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RIVERSIDE', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/woodl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'WOODLAND', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/waban']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'WABAN']},
    {'service': 'MBTA', 'args': {'pg': ['green/eliot']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ELIOT', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/newtn']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'NEWTON', 'GREEN', 'HIGHLANDS']},
    {'service': 'MBTA', 'args': {'pg': ['green/newto']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'NEWTON', 'CENTRE', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/chhil']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'HILL', 'GREEN', 'CHESTNUT']},
    {'service': 'MBTA', 'args': {'pg': ['green/rsmnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RESERVOIR', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/bcnfd']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'BEACONSFIELD']},
    {'service': 'MBTA', 'args': {'pg': ['green/brkhl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BROOKLINE', 'HILLS', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/bvmnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BROOKLINE', 'GREEN', 'VILLAGE']},
    {'service': 'MBTA', 'args': {'pg': ['green/longw']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'LONGWOOD']},
    {'service': 'MBTA', 'args': {'pg': ['green/fenwy']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'FENWAY', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/kencl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'KENMORE']},
    {'service': 'MBTA', 'args': {'pg': ['green/hymnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'HYNES', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/coecl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'COPLEY', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/armnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'ARLINGTON']},
    {'service': 'MBTA', 'args': {'pg': ['green/boyls']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BOYLSTON', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/hsmnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'HEATH']},
    {'service': 'MBTA', 'args': {'pg': ['green/bckhl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'THE', 'BACK', 'OF', 'HILL', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/rvrwy']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RIVERWAY', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/mispk']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'PARK', 'MISSION']},
    {'service': 'MBTA', 'args': {'pg': ['green/fenwd']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RD', 'GREEN', 'FENWOOD']},
    {'service': 'MBTA', 'args': {'pg': ['green/brmnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'CIRCLE', 'BRIGHAM', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/lngmd']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'AREA', 'GREEN', 'LONGWOOD', 'MEDICAL']},
    {'service': 'MBTA', 'args': {'pg': ['green/mfa']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'MUSEUM', 'FINE', 'GREEN', 'OF', 'ARTS']},
    {'service': 'MBTA', 'args': {'pg': ['green/nuniv']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'NORTHEASTERN', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/symcl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'SYMPHONY', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/prmnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'PRUDENTIAL', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/coecl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'COPLEY', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/armnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'ARLINGTON']},
    {'service': 'MBTA', 'args': {'pg': ['green/boyls']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BOYLSTON', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['green/spmnl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'END', 'PARK', 'SCIENCE', 'GREEN', 'WEST']},
    {'service': 'MBTA', 'args': {'pg': ['green/lech']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'GREEN', 'LECHMERE']},
    {'service': 'MBTA', 'args': {'pg': ['red/RALE']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'ALEWIFE']},
    {'service': 'MBTA', 'args': {'pg': ['red/RDAV']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'DAVIS', 'RED']},
    {'service': 'MBTA', 'args': {'pg': ['red/RPOR']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'SQ', 'PORTER', 'SQUARE']},
    {'service': 'MBTA', 'args': {'pg': ['red/RHAR']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'SQ', 'SQUARE', 'HARVARD']},
    {'service': 'MBTA', 'args': {'pg': ['red/RCEN']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'SQ', 'SQUARE', 'CENTRAL']},
    {'service': 'MBTA', 'args': {'pg': ['red/RKEN']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'MIT', 'KENDALL', 'RED']},
    {'service': 'MBTA', 'args': {'pg': ['red/RMGH']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'CHARLES', 'MGH']},
    {'service': 'MBTA', 'args': {'pg': ['red/RSOU']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'STATION', 'SOUTH']},
    {'service': 'MBTA', 'args': {'pg': ['red/RBRO']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'BROADWAY']},
    {'service': 'MBTA', 'args': {'pg': ['red/RAND']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ANDREW', 'RED']},
    {'service': 'MBTA', 'args': {'pg': ['red/RJFK']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'JFK', 'UMASS', 'RED']},
    {'service': 'MBTA', 'args': {'pg': ['red/RSAV']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'HILL', 'SAVIN', 'RED']},
    {'service': 'MBTA', 'args': {'pg': ['red/RFIE']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'FIELDS', 'CORNER']},
    {'service': 'MBTA', 'args': {'pg': ['red/RSHA']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'SHAWMUT']},
    {'service': 'MBTA', 'args': {'pg': ['red/RASH']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ASHMONT', 'RED']},
    {'service': 'MBTA', 'args': {'pg': ['red/RNQU']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'NORTH', 'QUINCY']},
    {'service': 'MBTA', 'args': {'pg': ['red/RWOL']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'WOLLASTON']},
    {'service': 'MBTA', 'args': {'pg': ['red/RQUC']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'QUINCY', 'CENTER']},
    {'service': 'MBTA', 'args': {'pg': ['red/RQUA']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'QUINCY', 'ADAMS']},
    {'service': 'MBTA', 'args': {'pg': ['red/RBRA']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'BRAINTREE']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OOAK']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'OAK', 'GROVE']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OMAL']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'MALDEN', 'CENTER']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OWEL']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'WELLINGTON']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OASM']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'ASSEMBLY']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OSUL']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'SULLIVAN', 'ORANGE']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OCOM']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'COLLEGE', 'COMMUNITY']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OCH']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'CHINATOWN']},
    {'service': 'MBTA', 'args': {'pg': ['orange/ONEM']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'TUFTS', 'MEDICAL']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OBAC']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BAY', 'ORANGE', 'BACK']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OMAS']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'AVE', 'MASS']},
    {'service': 'MBTA', 'args': {'pg': ['orange/ORUG']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'RUGGLES']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OROX']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'CROSSING', 'ORANGE', 'ROXBURY']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OJAC']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'JACKSON', 'SQ', 'SQUARE']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OSTO']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'BROOK', 'STONY']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OGRE']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'ST', 'STREET', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OFOR']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'HILLS', 'FOREST']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BWON']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'WONDERLAND']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BREV']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'REVERE', 'BEACH']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BBEA']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'BEACHMONT']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BSUF']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'SUFFOLK', 'DOWNS']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BORH']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'ORIENT', 'HEIGHTS']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BWOO']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'ISLAND', 'WOOD']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BAIR']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'AIRPORT']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BMAV']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'MAVERICK']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BAQU']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'AQUARIUM']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BBOW']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'BOWDOIN']},
    {'service': 'MBTA', 'args': {'pg': ['red/RPRK', 'green/pktrm']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'RED', 'ST', 'STREET', 'PARK', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OST', 'blue/BSTA']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'ST', 'STATE', 'STREET', 'BLUE']},
    {'service': 'MBTA', 'args': {'pg': ['orange/ODT', 'red/RDTC']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'CROSSING', 'ORANGE', 'DOWNTOWN', 'RED']},
    {'service': 'MBTA', 'args': {'pg': ['orange/ONST', 'green/north']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'NORTH', 'STATION', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['blue/BGOV', 'green/gover']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'BLUE', 'GOVERNMENT', 'CENTER', 'GREEN']},
    {'service': 'MBTA', 'args': {'pg': ['orange/OHAY', 'green/haecl']}, 'tags': ['MBTA', 'SUBWAY', 'T', 'SCHEDULE', 'LINE', 'ORANGE', 'HAYMARKET', 'GREEN']},
    {'args': {'category': None, 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['BREAKFAST', 'ALL']},
    {'args': {'category': 'BREAKFAST MEATS', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'BREAKFAST', 'MEATS']},
    {'args': {'category': 'BREAKFAST ENTREES', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'BREAKFAST', 'ENTREES']},
    {'args': {'category': 'BREAKFAST BAKERY', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'BREAKFAST', 'BAKERY']},
    {'args': {'category': 'BREAKFAST MISC', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'BREAKFAST', 'MISC']},
    {'args': {'category': 'BREAKFAST BREADS', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'BREAKFAST', 'BREADS']},
    {'args': {'category': 'STARCH & POTATOES', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'STARCH', 'POTATOES']},
    {'args': {'category': 'MAKE OR BUILD YOUR OWN', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'MAKE', 'BUILD', 'YOUR', 'OWN']},
    {'args': {'category': 'SPECIAL BARS - BOARD MENU', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'BOARD']},
    {'args': {'category': 'IN ADDITION AT ANNENBERG', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'ANNENBERG']},
    {'args': {'category': 'FRUIT', 'type': 'BREAKFAST'}, 'service': 'M', 'tags': ['MENU', 'BREAKFAST', 'FRUIT']},
    {'args': {'category': None, 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'ALL']},
    {'args': {'category': "TODAY'S SOUP", 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', "TODAY'S', 'SOUP"]},
    {'args': {'category': 'SALAD BAR', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'SALAD', 'BAR']},
    {'args': {'category': 'SANDWICH BAR', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'SANDWICH', 'BAR']},
    {'args': {'category': 'ENTREES', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'ENTREES']},
    {'args': {'category': 'VEGETARIAN ENTREE', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'VEGETARIAN', 'ENTREE']},
    {'args': {'category': 'STARCH & POTATOES', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'STARCH', 'POTATOES']},
    {'args': {'category': 'VEGETABLES', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'VEGETABLES']},
    {'args': {'category': 'DESSERTS', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'DESSERTS']},
    {'args': {'category': 'FROM THE GRILLE', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'GRILLE']},
    {'args': {'category': 'PLANT PROTEIN', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'PLANT', 'PROTEIN']},
    {'args': {'category': 'BROWN RICE STATION', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'BROWN', 'RICE', 'STATION']},
    {'args': {'category': 'ENTREE SALADS', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'ENTREE', 'SALADS']},
    {'args': {'category': 'SIDE SALADS', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'SIDE', 'SALADS']},
    {'args': {'category': 'FRUIT', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'FRUIT']},
    {'args': {'category': 'CHILI BAR', 'type': 'LUNCH'}, 'service': 'M', 'tags': ['MENU', 'LUNCH', 'CHILI', 'BAR']},
    {'args': {'category': None, 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'ALL']},
    {'args': {'category': "TODAY'S SOUP", 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', "TODAY'S', 'SOUP"]},
    {'args': {'category': 'SALAD BAR', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'SALAD', 'BAR']},
    {'args': {'category': 'ENTREES', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'ENTREES']},
    {'args': {'category': 'VEGETARIAN ENTREE', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'VEGETARIAN', 'ENTREE']},
    {'args': {'category': 'STARCH & POTATOES', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'STARCH', 'POTATOES']},
    {'args': {'category': 'VEGETABLES', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'VEGETABLES']},
    {'args': {'category': 'DESSERTS', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'DESSERTS']},
    {'args': {'category': 'BREAD,ROLLS, MISC BAKERY', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'BREAD', 'ROLLS', 'BAKERY']},
    {'args': {'category': 'FROM THE GRILLE', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'GRILLE']},
    {'args': {'category': 'PLANT PROTEIN', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'PLANT', 'PROTEIN']},
    {'args': {'category': 'BROWN RICE STATION', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'BROWN', 'RICE', 'STATION']},
    {'args': {'category': 'CULINARY DISPLAY', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'CULINARY', 'DISPLAY']},
    {'args': {'category': 'ENTREE SALADS', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'ENTREE', 'SALADS']},
    {'args': {'category': 'SIDE SALADS', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'SIDE', 'SALADS']},
    {'args': {'category': 'FRUIT', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'FRUIT']},
    {'args': {'category': 'WHOLE GRAIN PASTA BAR', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'WHOLE', 'GRAIN', 'PASTA', 'BAR']},
    {'args': {'category': 'BRAIN BREAK', 'type': 'DINNER'}, 'service': 'M', 'tags': ['MENU', 'DINNER', 'BRAIN', 'BREAK']}]
