
library = {
    "ANDOVER-HARVARD THEOLOGICAL LIBRARY" : "data-nid='1551'",
    "ARNOLD ARBORETUM HORTICULTURAL LIBRARY" : "data-nid='1600'",
    "ARTHUR AND ELIZABETH SCHLESINGER LIBRARY" : "data-nid='1553'",
    "BAKER LIBRARY" : "data-nid='1558'",
    "BAKER LIBRARY SPECIAL COLLECTIONS" : "data-nid='1559'",
    "BIBLIOTECA BERENSON" : "data-nid='1603'",
    "BIRKHOFF MATHEMATICAL LIBRARY" : "data-nid='1577'",
    "BOTANY LIBRARY" : "data-nid='1724'",
    "CABOT SCIENCE LIBRARY" : "data-nid='1578'",
    "CHEMISTRY AND CHEMICAL BIOLOGY LIBRARY" : "data-nid='1580'",
    "COUNTWAY LIBRARY OF MEDICINE" : "data-nid='2575'",
    "DUMBARTON OAKS" : "data-nid='1618'",
    "LOEB MUSIC LIBRARY" : "data-nid='1592'",
    "ERNST MAYR LIBRARY" : "data-nid='1539'",
    "FINE ARTS LIBRARY" : "data-nid='1576'",
    "FUNG LIBRARY" : "data-nid='1581'",
    "GOVERNMENT DOCUMENTS AND MICROFORMS COLLECTION" : "data-nid='1572'",
    "GROSSMAN LIBRARY" : "data-nid='1536'",
    "HARVARD FILM ARCHIVE" : "data-nid='1582'",
    "HARVARD KENNEDY SCHOOL LIBRARY" : "data-nid='1535'",
    "HARVARD LAW SCHOOL LIBRARY" : "data-nid='1565'",
    "HARVARD MAP COLLECTION" : "data-nid='1583'",
    "PUSEY LIBRARY" : "data-nid='3359'",
    "HOUGHTON LIBRARY" : "data-nid='1591'",
    "YENCHING LIBRARY" : "data-nid='1584'",
    "LAMONT LIBRARY" : "data-nid='1571'",
    "MONROE C. GUTMAN LIBRARY" : "data-nid='1533'",
    "PHYSICS RESEARCH LIBRARY" : "data-nid='1595'",
    "ROBBINS LIBRARY OF PHILOSOPHY" : "data-nid='4101'",
    "TOZZER LIBRARY" : "data-nid='1596'",
    "WIDENER LIBRARY" : "data-nid='1567'",
    "WOLBACH LIBRARY" : "data-nid='1602'"

}